name: clean artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: glassechidna/artifact-cleaner@master
        with:
          minimumAge: 86400 # all artifacts at least one day old
